### ISSUE TITLE
UI breaks in wsl

### ISSUE THREAD

**Issue by AviAvinav** [thatvegandev/gh-eco#1]
## Description

I am using fish shell on WSL (Windows Subsystem for Linux) and the UI breaks down for user profiles, the readme section seems fine though.

I tested it in bash too and the result is the same.

## To Reproduce

Install WSL, gh and gh-eco and run `gh eco`.

## Expected behavior

I was expecting to see the same UI as in the README of this project.

## Screenshots

<img src="https://i.ibb.co/QvHLpmJ/gh-eco-ui-bug.png" />

## Environment

- OS: Ubuntu in WSL
- Terminal Emulator: Fish shell
- Font: JetBrainsMono Nerd Font
- `gh-eco` version: v0.1.0

**Comment by jrnxf** [comment]
Hey @AviAvinav! I'm willing to bet this has to do with the fact your window size / font size is not generous enough. Can you try making either (or both) your terminal window sizer bigger or your font size smaller? This really is meant to be more of a full screen tui!

**Comment by AviAvinav** [comment]
The terminal was already at full screen, but the problem is the font size it seems. I tried it out with different font sizes, and it seems to start breaking at font size of 11 points in windows terminal.

**Comment by jrnxf** [comment]
Yeah that's what I figured! This is a known limitation of gh-eco, and one I personally don't feel necessitates a fix. At least not now. And here's why:

Let's play out the scenario where I do attempt to fix this...

Given the current layout the one thing I cannot make smaller is the contribution graph. (I could remove the spaces in-between the cells but that looks terrible. The only option I'm left with is to remove the graph from the display entirely. If I then threw the pinned repos in one column I'd be in better shape, but then the entire page layout would easily extend past the terminal height (see image). Now I need to redefine my keybindings so I can scroll and tab. It's also easy to run into issues with word wrapping at that point. How much of the repo description can I actually show now? It's all just an endless void of edge cases, which is why I'm ultimately not interested in make responsive design a theme of this project at this point in time.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/21346716/171805215-f8b31022-b28f-42b0-b698-229bfe1209de.png">
